services:
  agent:
    env_file: [.env]
    environment:
      WAIT_HOSTS: "entity-extraction:9103, wiki-parser:9077"
      WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-480}
    build:
      args:
        PORT: 9999
        SRC_DIR: agent/
      context: ./
      dockerfile: agent/Dockerfile
    volumes:
      - ./agent:/src/agent
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 64M

  entity-extraction:
    build:
      args:
        NER_CONFIG: entity_detection_en.json
        EL_CONFIG: entity_linking_en_full.json
        PORT: 9103
        SRC_DIR: annotators/entity_extraction/
        INCLUDE_MISC: 1
      context: ./
      dockerfile: annotators/entity_extraction/Dockerfile
    ports:
      - 9103:9103
    volumes:
      - ./annotators/entity_extraction:/src
      - ~/.deeppavlov:/root/.deeppavlov
    environment:
      - CUDA_VISIBLE_DEVICES=''
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 2G

  wiki-parser:
    env_file: [.env]
    build:
      args:
        WIKI_LITE_DB: http://files.deeppavlov.ai/kbqa/wikidata/wikidata_lite.hdt
        WIKI_LITE_INDEX_DB: http://files.deeppavlov.ai/kbqa/wikidata/wikidata_lite.hdt.index.v1-1
        WIKI_CACHE_DB: http://files.deeppavlov.ai/kbqa/wikidata/wikidata_cache.json
        CONFIG: wiki_parser.json
        PORT: 9077
        SRC_DIR: annotators/wiki_parser
        COMMIT: ff5b156d16a949c3ec99da7fb60ae907dec37a41
      context: ./
      dockerfile: annotators/wiki_parser/Dockerfile
    command: flask run -h 0.0.0.0 -p 9077
    ports:
      - 9077:9077
    environment:
      - CUDA_VISIBLE_DEVICES=''
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

version: '3.7'
