name: Full API Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        run: |
          touch .env
          echo AGENT_URL=http://localhost:9999/ >> .env
          echo ENTITY_EXTRACTION_URL=http://localhost:9103/entity_extraction >> .env
          echo ENTITY_DETECTION_URL=http://localhost:9103/model >> .env
          echo ENTITY_LINKING_URL=http://localhost:9075/model >> .env
          echo WIKI_PARSER_URL=http://localhost:9077/model >> .env
          cat .env
      - name: Build the stack
        run: docker-compose up -d
      - name: Wait Docker-Compose
        # You may pin to the exact commit or the version.
        # uses: thegabriele97/dockercompose-health-action@f09b093cb0b4235770a5525d6ab3487dc5d203f2
        uses: thegabriele97/dockercompose-health-action@v1.0
        with:
          # After timeout seconds, the wait process fails returning Status Code 1
          timeout: '120'
          # The directory where your docker-compose.yml is
          workdir: '.'
      - name: Collect Docker Logs
        uses: jwalton/gh-docker-logs@v2.2.0
      - name: Test
        run: docker run --network container:entity_extraction_svc_agent_1 appropriate/curl --verbose -s --retry 10 --retry-connrefused http://localhost:9999/
