name: Full API Test

on:
  push:
    branches: [ "feat/workflows" ]
  pull_request:
    branches: [ "feat/workflows" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        run: |
          touch .env
          echo AGENT_URL=http://agent:9999/ >> .env
          echo ENTITY_EXTRACTION_URL=http://entity-extraction:9103/entity_extraction >> .env
          echo ENTITY_DETECTION_URL=http://entity-detection:9103/model >> .env
          echo ENTITY_LINKING_URL=http://entity-linking:9075/model >> .env
          echo WIKI_PARSER_URL=http://wiki-parser:9077/model >> .env
          cat .env
      - name: Build
        run: docker-compose up -d
      - name: Wait until deployed
        run: |
          docker run --network container:entity_extraction_svc_agent_1 appropriate/curl \
            -4 \
            --verbose \
            --connect-timeout 10 \
            --max-time 10 \
            --retry 30 \
            --retry-delay 20 \
            --retry-connrefused \
            --url http://localhost:9999/health
      - name: Docker logs dump on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2.2.0
      - name: Final docker logs dump
        uses: jwalton/gh-docker-logs@v2.2.0
