name: Full API Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker run --network container:agent appropriate/curl -s --retry 10 --retry-connrefused http://localhost:9999/
